name: Generate terraform docs
on:
  - pull_request
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate TF docs
        uses: terraform-docs/gh-actions@v1
        with:
          git-push: "true"
          config-file: .terraform-docs.yml
